version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - "./docker.env"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"
      depends_on:
        - redis